### PR TITLE
Introduce `NestedMap` preserving XML sequence order

### PR DESCRIPTION
**Pull request by am-kantox**
This is a proposal to add another kind of map structure (`NestedMap`) in addition to `NaiveMap`.

The type of this map is 
```elixir 
  @type element :: %{
          name: String.t(),
          attributes: map() | [{charlist() | String.t(), charlist() | String.t()}],
          content: [element()]
        }
```

It preserves the order of collections from _XML_ and might be safely converted back to _XML_ if needed. It brings some benefits when the shape is not pre-defined and some kind of automated parsing of the resulting map is expected.

WDYT?

### CODE REVIEW

**Comment by hchou-godaddy** [comment]
👀  Oooo cool!  I like how it returns a consistent recursive data structure.  Nice work!  Can you also update the README text with your new function and then bump the package version number, and I'll merge.  ❤️

**Comment by homanchou** [comment]
👀  Oooo cool!  I like how it returns a consistent recursive data structure.  Nice work!  Can you also update the README text with your new function and then bump the package version number, and I'll merge.  ❤️

**Comment by am-kantox** [comment]
Done, and I added a parameter to purge empty content and attributes because they now have default values.

**Review by homanchou — APPROVED** [review]
LGTM ❤️

**Comment by homanchou** [comment]
Hmmm... attempting to publish to hex (which I haven't done in a while) and getting this error.  I haven't been able to goole my way out of it.  any suggestions?

```
mix hex.publish
Building elixir_xml_to_map 3.1.0
  Dependencies:
    erlsom ~> 1.4 (app: erlsom)
  App: elixir_xml_to_map
  Name: elixir_xml_to_map
  Files:
    lib
    lib/elixir_xml_to_map.ex
    lib/xml_to_map
    lib/xml_to_map/naive_map.ex
    lib/xml_to_map/nested_map.ex
    .formatter.exs
    mix.exs
    README.md
    LICENSE
  Version: 3.1.0
  Build tools: mix
  Description: A module for converting an XML string to a map
  Licenses: Apache-2.0
  Links:
    GitHub: https://github.com/homanchou/elixir-xml-to-map
  Elixir: ~> 1.9
Before publishing, please read the Code of Conduct: https://hex.pm/policies/codeofconduct

Publishing package to public repository hexpm.

Proceed? [Yn] Y
Building docs...
** (ArgumentError) unknown application: :hex
    (elixir 1.15.5) lib/application.ex:1010: Application.app_dir/1
    (elixir 1.15.5) lib/application.ex:1037: Application.app_dir/2
    (ex_doc 0.21.3) lib/ex_doc/formatter/html/autolink.ex:623: ExDoc.Formatter.HTML.Autolink.hex_lib_dirs/0
    (ex_doc 0.21.3) lib/ex_doc/formatter/html/autolink.ex:549: ExDoc.Formatter.HTML.Autolink.default_lib_dirs/1
    (ex_doc 0.21.3) lib/ex_doc/formatter/html/autolink.ex:546: ExDoc.Formatter.HTML.Autolink.default_lib_dirs/0
    (ex_doc 0.21.3) lib/ex_doc/formatter/html/autolink.ex:92: ExDoc.Formatter.HTML.Autolink.compile/3
    (ex_doc 0.21.3) lib/ex_doc/formatter/html.ex:68: ExDoc.Formatter.HTML.autolink_and_render/4
    (ex_doc 0.21.3) lib/ex_doc/formatter/html.ex:21: ExDoc.Formatter.HTML.run/2
```

**Comment by am-kantox** [comment]
> `** (ArgumentError) unknown application: :hex`

I was able to reproduce it, `mix docs` failed due to some obsoleteness in `mix.lock` file.

`rm -rf mix.lock && mix deps.get` fixes it.

**Comment by am-kantox** [comment]
@homanchou ping did the pill above help?

**Comment by homanchou** [comment]
Ah, I didn’t get a chance to try it yet. Not home right now. Will try it as
soon as I can.

**Comment by homanchou** [comment]
New error:

***@***.***:~/web_projects/elixir-xml-to-map$ rm -rf mix.lock && mix
deps.get
Resolving Hex dependencies...
Resolution completed in 0.114s
New:
  earmark_parser 1.4.39
  erlsom 1.5.1
  ex_doc 0.31.1
  makeup 1.1.1
  makeup_elixir 0.16.1
  makeup_erlang 0.1.4
  nimble_parsec 1.4.0
All dependencies are up to date
***@***.***:~/web_projects/elixir-xml-to-map$ mix hex.publish
Building elixir_xml_to_map 3.1.0
  Dependencies:
    erlsom ~> 1.4 (app: erlsom)
  App: elixir_xml_to_map
  Name: elixir_xml_to_map
  Files:
    lib
    lib/elixir_xml_to_map.ex
    lib/xml_to_map
    lib/xml_to_map/naive_map.ex
    lib/xml_to_map/nested_map.ex
    .formatter.exs
    mix.exs
    README.md
    LICENSE
  Version: 3.1.0
  Build tools: mix
  Description: A module for converting an XML string to a map
  Licenses: Apache-2.0
  Links:
    GitHub: https://github.com/homanchou/elixir-xml-to-map
  Elixir: ~> 1.9
Before publishing, please read the Code of Conduct:
https://hex.pm/policies/codeofconduct

Publishing package to public repository hexpm.

Proceed? [Yn] Y
Building docs...
** (MatchError) no match of right hand side value: {:error, {:earmark,
{~c"no such file or directory", ~c"earmark.app"}}}
    (ex_doc 0.21.3) lib/mix/tasks/docs.ex:302: Mix.Tasks.Docs.run/3
    (mix 1.15.7) lib/mix/task.ex:455: anonymous fn/3 in Mix.Task.run_task/5
    (hex 2.0.6) lib/mix/tasks/hex.publish.ex:191:
Mix.Tasks.Hex.Publish.docs_task/0
    (hex 2.0.6) lib/mix/tasks/hex.publish.ex:146:
Mix.Tasks.Hex.Publish.create/3
    (mix 1.15.7) lib/mix/task.ex:455: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.7) lib/mix/cli.ex:92: Mix.CLI.run_task/2
    /home/titan/.asdf/installs/elixir/1.15.7-otp-26/bin/mix:2: (file)

**Comment by am-kantox** [comment]
`rm -rf _build` and retry?

**Comment by homanchou** [comment]
That did the trick!  published!

**Comment by am-kantox** [comment]
@homanchou unfortunately, it’s not published 
```
❯ mix hex.info elixir_xml_to_map
A module for converting an XML string to a map

Config: {:elixir_xml_to_map, "~> 3.0"}
Locked version: 3.0.0
Releases: 3.0.0, 2.0.0, 1.0.1, 1.0.0, 0.2.0, 0.1.3, 0.1.2, 0.1.1, ...

Licenses: Apache-2.0
Links:
  GitHub: https://github.com/homanchou/elixir-xml-to-map

```

**Comment by am-kantox** [comment]
> That did the trick! published!

Sorry for bothering you, but `v3.1.0` did not reach `hex.pm`. Would you please try to publish it again when you have time? Thanks!

**Comment by homanchou** [comment]
Ah!  now it's published!  I wonder what happened, maybe it prompted for a final confirmation that I overlooked the first time.  Sorry about the delay.  And thanks again.

**Pull request merged**
